//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elegant.Ui.Samples.ControlsSample.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elegant.Ui.Samples.ControlsSample.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AirBrushHardRound13px {
            get {
                object obj = ResourceManager.GetObject("AirBrushHardRound13px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AirBrushHardRound19px {
            get {
                object obj = ResourceManager.GetObject("AirBrushHardRound19px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AirBrushHardRound9px {
            get {
                object obj = ResourceManager.GetObject("AirBrushHardRound9px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackgroundColorPickerImage {
            get {
                object obj = ResourceManager.GetObject("BackgroundColorPickerImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BasicNaryOperators01 {
            get {
                object obj = ResourceManager.GetObject("BasicNaryOperators01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BasicNaryOperators02 {
            get {
                object obj = ResourceManager.GetObject("BasicNaryOperators02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BasicNaryOperators03 {
            get {
                object obj = ResourceManager.GetObject("BasicNaryOperators03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BasicNaryOperators04 {
            get {
                object obj = ResourceManager.GetObject("BasicNaryOperators04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BasicNaryOperators05 {
            get {
                object obj = ResourceManager.GetObject("BasicNaryOperators05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BasicNaryOperators06 {
            get {
                object obj = ResourceManager.GetObject("BasicNaryOperators06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BasicNaryOperators07 {
            get {
                object obj = ResourceManager.GetObject("BasicNaryOperators07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BasicNaryOperators08 {
            get {
                object obj = ResourceManager.GetObject("BasicNaryOperators08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BasicNaryOperators09 {
            get {
                object obj = ResourceManager.GetObject("BasicNaryOperators09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BasicNaryOperators10 {
            get {
                object obj = ResourceManager.GetObject("BasicNaryOperators10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BasicNaryOperators11 {
            get {
                object obj = ResourceManager.GetObject("BasicNaryOperators11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BasicNaryOperators12 {
            get {
                object obj = ResourceManager.GetObject("BasicNaryOperators12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BasicNaryOperators13 {
            get {
                object obj = ResourceManager.GetObject("BasicNaryOperators13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Black32x32 {
            get {
                object obj = ResourceManager.GetObject("Black32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Blue32x32 {
            get {
                object obj = ResourceManager.GetObject("Blue32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BlueCircle_27x27 {
            get {
                object obj = ResourceManager.GetObject("BlueCircle_27x27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BorderColorPickerImage {
            get {
                object obj = ResourceManager.GetObject("BorderColorPickerImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushChalk36px {
            get {
                object obj = ResourceManager.GetObject("BrushChalk36px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushCharcoalLargeSmear36px {
            get {
                object obj = ResourceManager.GetObject("BrushCharcoalLargeSmear36px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushDryBrush39px {
            get {
                object obj = ResourceManager.GetObject("BrushDryBrush39px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushDryBrushTipLightFlow66px {
            get {
                object obj = ResourceManager.GetObject("BrushDryBrushTipLightFlow66px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushDuneGrass112px {
            get {
                object obj = ResourceManager.GetObject("BrushDuneGrass112px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushFlowingStars29px {
            get {
                object obj = ResourceManager.GetObject("BrushFlowingStars29px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushFuzzball192px {
            get {
                object obj = ResourceManager.GetObject("BrushFuzzball192px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushGrass134px {
            get {
                object obj = ResourceManager.GetObject("BrushGrass134px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushHardPastelOnCanvas33px {
            get {
                object obj = ResourceManager.GetObject("BrushHardPastelOnCanvas33px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushHardRound13px {
            get {
                object obj = ResourceManager.GetObject("BrushHardRound13px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushHardRound19px {
            get {
                object obj = ResourceManager.GetObject("BrushHardRound19px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushHardRound1px {
            get {
                object obj = ResourceManager.GetObject("BrushHardRound1px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushHardRound3px {
            get {
                object obj = ResourceManager.GetObject("BrushHardRound3px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushHardRound5px {
            get {
                object obj = ResourceManager.GetObject("BrushHardRound5px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushHardRound9px {
            get {
                object obj = ResourceManager.GetObject("BrushHardRound9px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushOilPastelLarge63px {
            get {
                object obj = ResourceManager.GetObject("BrushOilPastelLarge63px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushScatteredLeaves95px {
            get {
                object obj = ResourceManager.GetObject("BrushScatteredLeaves95px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushScatteredMapleLeaves74px {
            get {
                object obj = ResourceManager.GetObject("BrushScatteredMapleLeaves74px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushSoftRound13px {
            get {
                object obj = ResourceManager.GetObject("BrushSoftRound13px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushSoftRound17px {
            get {
                object obj = ResourceManager.GetObject("BrushSoftRound17px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushSoftRound21px {
            get {
                object obj = ResourceManager.GetObject("BrushSoftRound21px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushSoftRound27px {
            get {
                object obj = ResourceManager.GetObject("BrushSoftRound27px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushSoftRound5px {
            get {
                object obj = ResourceManager.GetObject("BrushSoftRound5px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushSoftRound9px {
            get {
                object obj = ResourceManager.GetObject("BrushSoftRound9px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushSpatter14px {
            get {
                object obj = ResourceManager.GetObject("BrushSpatter14px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushSpatter24px {
            get {
                object obj = ResourceManager.GetObject("BrushSpatter24px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushSpatter27px {
            get {
                object obj = ResourceManager.GetObject("BrushSpatter27px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushSpatter39px {
            get {
                object obj = ResourceManager.GetObject("BrushSpatter39px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushSpatter46px {
            get {
                object obj = ResourceManager.GetObject("BrushSpatter46px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BrushSpatter59px {
            get {
                object obj = ResourceManager.GetObject("BrushSpatter59px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Callouts1_Small {
            get {
                object obj = ResourceManager.GetObject("Callouts1_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Callouts2_Small {
            get {
                object obj = ResourceManager.GetObject("Callouts2_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Callouts3_Small {
            get {
                object obj = ResourceManager.GetObject("Callouts3_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Callouts4_Small {
            get {
                object obj = ResourceManager.GetObject("Callouts4_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CircleTemperatureIndicator {
            get {
                object obj = ResourceManager.GetObject("CircleTemperatureIndicator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DoubleDownArrow {
            get {
                object obj = ResourceManager.GetObject("DoubleDownArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DoubleLeftArrow {
            get {
                object obj = ResourceManager.GetObject("DoubleLeftArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DoubleRightArrow {
            get {
                object obj = ResourceManager.GetObject("DoubleRightArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DoubleTopArrow {
            get {
                object obj = ResourceManager.GetObject("DoubleTopArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DownArrow {
            get {
                object obj = ResourceManager.GetObject("DownArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon ElegantIcon {
            get {
                object obj = ResourceManager.GetObject("ElegantIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ElegantUI_01 {
            get {
                object obj = ResourceManager.GetObject("ElegantUI_01", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ElegantUI_02 {
            get {
                object obj = ResourceManager.GetObject("ElegantUI_02", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ElegantUI_03 {
            get {
                object obj = ResourceManager.GetObject("ElegantUI_03", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ElegantUI_04 {
            get {
                object obj = ResourceManager.GetObject("ElegantUI_04", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ElegantUI_05 {
            get {
                object obj = ResourceManager.GetObject("ElegantUI_05", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ElegantUI_06 {
            get {
                object obj = ResourceManager.GetObject("ElegantUI_06", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ElegantUI_07 {
            get {
                object obj = ResourceManager.GetObject("ElegantUI_07", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ElegantUI_08 {
            get {
                object obj = ResourceManager.GetObject("ElegantUI_08", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ElegantUI_09 {
            get {
                object obj = ResourceManager.GetObject("ElegantUI_09", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ElegantUI_10 {
            get {
                object obj = ResourceManager.GetObject("ElegantUI_10", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ElegantUI_11 {
            get {
                object obj = ResourceManager.GetObject("ElegantUI_11", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ElegantUI_12 {
            get {
                object obj = ResourceManager.GetObject("ElegantUI_12", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ElegantUI_13 {
            get {
                object obj = ResourceManager.GetObject("ElegantUI_13", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ElegantUI_14 {
            get {
                object obj = ResourceManager.GetObject("ElegantUI_14", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ElegantUI_15 {
            get {
                object obj = ResourceManager.GetObject("ElegantUI_15", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ElegantUI_16 {
            get {
                object obj = ResourceManager.GetObject("ElegantUI_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ElegantUI_17 {
            get {
                object obj = ResourceManager.GetObject("ElegantUI_17", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ElegantUI_18 {
            get {
                object obj = ResourceManager.GetObject("ElegantUI_18", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon ElegantUI_19 {
            get {
                object obj = ResourceManager.GetObject("ElegantUI_19", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EncryptDocument_Large {
            get {
                object obj = ResourceManager.GetObject("EncryptDocument_Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fall1 {
            get {
                object obj = ResourceManager.GetObject("Fall1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fall10 {
            get {
                object obj = ResourceManager.GetObject("Fall10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fall11 {
            get {
                object obj = ResourceManager.GetObject("Fall11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fall12 {
            get {
                object obj = ResourceManager.GetObject("Fall12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fall2 {
            get {
                object obj = ResourceManager.GetObject("Fall2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fall3 {
            get {
                object obj = ResourceManager.GetObject("Fall3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fall4 {
            get {
                object obj = ResourceManager.GetObject("Fall4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fall5 {
            get {
                object obj = ResourceManager.GetObject("Fall5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fall6 {
            get {
                object obj = ResourceManager.GetObject("Fall6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fall7 {
            get {
                object obj = ResourceManager.GetObject("Fall7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fall8 {
            get {
                object obj = ResourceManager.GetObject("Fall8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Fall9 {
            get {
                object obj = ResourceManager.GetObject("Fall9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FullScreenReadingSmall {
            get {
                object obj = ResourceManager.GetObject("FullScreenReadingSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenCircle_27x27 {
            get {
                object obj = ResourceManager.GetObject("GreenCircle_27x27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenPaper {
            get {
                object obj = ResourceManager.GetObject("GreenPaper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenPaperSmall {
            get {
                object obj = ResourceManager.GetObject("GreenPaperSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ID_DV_DRAFT_SMALL {
            get {
                object obj = ResourceManager.GetObject("ID_DV_DRAFT_SMALL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ID_DV_OUTLINE_SMALL {
            get {
                object obj = ResourceManager.GetObject("ID_DV_OUTLINE_SMALL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ID_DV_WEB_LAYOUT_SMALL {
            get {
                object obj = ResourceManager.GetObject("ID_DV_WEB_LAYOUT_SMALL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ID_INSERT_BOOKMARK_LARGE {
            get {
                object obj = ResourceManager.GetObject("ID_INSERT_BOOKMARK_LARGE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ID_INSERT_BOOKMARK_LARGE_GREEN {
            get {
                object obj = ResourceManager.GetObject("ID_INSERT_BOOKMARK_LARGE_GREEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ID_INSERT_BOOKMARK_SMALL {
            get {
                object obj = ResourceManager.GetObject("ID_INSERT_BOOKMARK_SMALL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ID_INSERT_BOOKMARK_SMALL_GREEN {
            get {
                object obj = ResourceManager.GetObject("ID_INSERT_BOOKMARK_SMALL_GREEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ID_INSERT_CHART_LARGE {
            get {
                object obj = ResourceManager.GetObject("ID_INSERT_CHART_LARGE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ID_INSERT_CHART_LARGE_PENSIL {
            get {
                object obj = ResourceManager.GetObject("ID_INSERT_CHART_LARGE_PENSIL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ID_INSERT_CHART_SMALL {
            get {
                object obj = ResourceManager.GetObject("ID_INSERT_CHART_SMALL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ID_INSERT_CHART_SMALL_PENSIL {
            get {
                object obj = ResourceManager.GetObject("ID_INSERT_CHART_SMALL_PENSIL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ID_INSERT_CROSS_REFERENCE_LARGE {
            get {
                object obj = ResourceManager.GetObject("ID_INSERT_CROSS_REFERENCE_LARGE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ID_INSERT_CROSS_REFERENCE_SMALL {
            get {
                object obj = ResourceManager.GetObject("ID_INSERT_CROSS_REFERENCE_SMALL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ID_INSERT_EQUATION_LARGE {
            get {
                object obj = ResourceManager.GetObject("ID_INSERT_EQUATION_LARGE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ID_INSERT_EQUATION_SMALL {
            get {
                object obj = ResourceManager.GetObject("ID_INSERT_EQUATION_SMALL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ID_INSERT_PICTURE_FROM_FILE_LARGE {
            get {
                object obj = ResourceManager.GetObject("ID_INSERT_PICTURE_FROM_FILE_LARGE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ID_INSERT_PICTURE_FROM_FILE_SMALL {
            get {
                object obj = ResourceManager.GetObject("ID_INSERT_PICTURE_FROM_FILE_SMALL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ID_INSERT_QUICK_PARTS_LARGE {
            get {
                object obj = ResourceManager.GetObject("ID_INSERT_QUICK_PARTS_LARGE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ID_INSERT_QUICK_PARTS_LARGE_COLOR {
            get {
                object obj = ResourceManager.GetObject("ID_INSERT_QUICK_PARTS_LARGE_COLOR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ID_INSERT_QUICK_PARTS_SMALL {
            get {
                object obj = ResourceManager.GetObject("ID_INSERT_QUICK_PARTS_SMALL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ID_INSERT_QUICK_PARTS_SMALL_COLOR {
            get {
                object obj = ResourceManager.GetObject("ID_INSERT_QUICK_PARTS_SMALL_COLOR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ID_INSERT_SHAPES_LARGE {
            get {
                object obj = ResourceManager.GetObject("ID_INSERT_SHAPES_LARGE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ID_PARAGRAPH_SORT {
            get {
                object obj = ResourceManager.GetObject("ID_PARAGRAPH_SORT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Insert_ClipArt_Large {
            get {
                object obj = ResourceManager.GetObject("Insert_ClipArt_Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InsertCitation_Large {
            get {
                object obj = ResourceManager.GetObject("InsertCitation_Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InspectDocument_Large {
            get {
                object obj = ResourceManager.GetObject("InspectDocument_Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Italic {
            get {
                object obj = ResourceManager.GetObject("Italic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftArrow {
            get {
                object obj = ResourceManager.GetObject("LeftArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftRightArrow {
            get {
                object obj = ResourceManager.GetObject("LeftRightArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LeftSubscriptSuperscript_Large {
            get {
                object obj = ResourceManager.GetObject("LeftSubscriptSuperscript_Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MarkAsFinal_Large {
            get {
                object obj = ResourceManager.GetObject("MarkAsFinal_Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MarkEntry_Large {
            get {
                object obj = ResourceManager.GetObject("MarkEntry_Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MenyPlasementArea31 {
            get {
                object obj = ResourceManager.GetObject("MenyPlasementArea31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Office2007Black {
            get {
                object obj = ResourceManager.GetObject("Office2007Black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Office2007Blue {
            get {
                object obj = ResourceManager.GetObject("Office2007Blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Office2007Silver {
            get {
                object obj = ResourceManager.GetObject("Office2007Silver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Office2010Blue {
            get {
                object obj = ResourceManager.GetObject("Office2010Blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OrangeCircle_27x27 {
            get {
                object obj = ResourceManager.GetObject("OrangeCircle_27x27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Phone {
            get {
                object obj = ResourceManager.GetObject("Phone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PictureToolsQuickStyles_Large {
            get {
                object obj = ResourceManager.GetObject("PictureToolsQuickStyles_Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PrintLayoutSmall {
            get {
                object obj = ResourceManager.GetObject("PrintLayoutSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PurpleCircle_27x27 {
            get {
                object obj = ResourceManager.GetObject("PurpleCircle_27x27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RecordMacro {
            get {
                object obj = ResourceManager.GetObject("RecordMacro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedCircle_27x27 {
            get {
                object obj = ResourceManager.GetObject("RedCircle_27x27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedPaper {
            get {
                object obj = ResourceManager.GetObject("RedPaper", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RedPaperSmall {
            get {
                object obj = ResourceManager.GetObject("RedPaperSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reject_small {
            get {
                object obj = ResourceManager.GetObject("reject_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap research_small {
            get {
                object obj = ResourceManager.GetObject("research_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap resetpicture_small {
            get {
                object obj = ResourceManager.GetObject("resetpicture_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reviewingpane_small {
            get {
                object obj = ResourceManager.GetObject("reviewingpane_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reviewingpanevertical_small {
            get {
                object obj = ResourceManager.GetObject("reviewingpanevertical_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RightArrow {
            get {
                object obj = ResourceManager.GetObject("RightArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rotateleft_small {
            get {
                object obj = ResourceManager.GetObject("rotateleft_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap setlanguage_small {
            get {
                object obj = ResourceManager.GetObject("setlanguage_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sigma {
            get {
                object obj = ResourceManager.GetObject("sigma", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Silver32x32 {
            get {
                object obj = ResourceManager.GetObject("Silver32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spring1 {
            get {
                object obj = ResourceManager.GetObject("Spring1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spring2 {
            get {
                object obj = ResourceManager.GetObject("Spring2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spring3 {
            get {
                object obj = ResourceManager.GetObject("Spring3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spring4 {
            get {
                object obj = ResourceManager.GetObject("Spring4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spring5 {
            get {
                object obj = ResourceManager.GetObject("Spring5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spring6 {
            get {
                object obj = ResourceManager.GetObject("Spring6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spring7 {
            get {
                object obj = ResourceManager.GetObject("Spring7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spring8 {
            get {
                object obj = ResourceManager.GetObject("Spring8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Subscript_Large {
            get {
                object obj = ResourceManager.GetObject("Subscript_Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SubscriptSuperscript_Large {
            get {
                object obj = ResourceManager.GetObject("SubscriptSuperscript_Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Summer1 {
            get {
                object obj = ResourceManager.GetObject("Summer1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Summer2 {
            get {
                object obj = ResourceManager.GetObject("Summer2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Summer3 {
            get {
                object obj = ResourceManager.GetObject("Summer3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Summer4 {
            get {
                object obj = ResourceManager.GetObject("Summer4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Summer5 {
            get {
                object obj = ResourceManager.GetObject("Summer5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Summer6 {
            get {
                object obj = ResourceManager.GetObject("Summer6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Summer7 {
            get {
                object obj = ResourceManager.GetObject("Summer7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Summer8 {
            get {
                object obj = ResourceManager.GetObject("Summer8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sun {
            get {
                object obj = ResourceManager.GetObject("Sun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Superscript_Large {
            get {
                object obj = ResourceManager.GetObject("Superscript_Large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Symbols_Small {
            get {
                object obj = ResourceManager.GetObject("Symbols_Small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap System {
            get {
                object obj = ResourceManager.GetObject("System", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TabControlCustomToolbarFolder {
            get {
                object obj = ResourceManager.GetObject("TabControlCustomToolbarFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TabControlCustomToolbarPlus {
            get {
                object obj = ResourceManager.GetObject("TabControlCustomToolbarPlus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TanCircle_27x27 {
            get {
                object obj = ResourceManager.GetObject("TanCircle_27x27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TextBoxImage {
            get {
                object obj = ResourceManager.GetObject("TextBoxImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap themes_small {
            get {
                object obj = ResourceManager.GetObject("themes_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tight_small {
            get {
                object obj = ResourceManager.GetObject("tight_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap translationscreentip_small {
            get {
                object obj = ResourceManager.GetObject("translationscreentip_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpArrow {
            get {
                object obj = ResourceManager.GetObject("UpArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap UpDownArrow {
            get {
                object obj = ResourceManager.GetObject("UpDownArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Windows7 {
            get {
                object obj = ResourceManager.GetObject("Windows7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Winter1 {
            get {
                object obj = ResourceManager.GetObject("Winter1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Winter10 {
            get {
                object obj = ResourceManager.GetObject("Winter10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Winter2 {
            get {
                object obj = ResourceManager.GetObject("Winter2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Winter3 {
            get {
                object obj = ResourceManager.GetObject("Winter3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Winter4 {
            get {
                object obj = ResourceManager.GetObject("Winter4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Winter5 {
            get {
                object obj = ResourceManager.GetObject("Winter5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Winter6 {
            get {
                object obj = ResourceManager.GetObject("Winter6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Winter7 {
            get {
                object obj = ResourceManager.GetObject("Winter7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Winter8 {
            get {
                object obj = ResourceManager.GetObject("Winter8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Winter9 {
            get {
                object obj = ResourceManager.GetObject("Winter9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wordoptions_small {
            get {
                object obj = ResourceManager.GetObject("wordoptions_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap YellowCircle_27x27 {
            get {
                object obj = ResourceManager.GetObject("YellowCircle_27x27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
