use WeDo_DB 

CREATE TABLE `t_bookmark_menu` (
  `S_MENU_CD` varchar(2) NOT NULL,
  `L_MENU_CD` varchar(3) NOT NULL,
  PRIMARY KEY (`S_MENU_CD`,`L_MENU_CD`),
  KEY `idx_T_BOOKMARK_MENU01` (`S_MENU_CD`,`L_MENU_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=euckr;

CREATE TABLE `t_call_history` (
  `TONG_START_TIME` varchar(14) NOT NULL,
  `TONG_END_TIME` varchar(14) DEFAULT NULL,
  `CALL_TYPE` varchar(1) DEFAULT NULL,
  `ANI` varchar(20) DEFAULT NULL,
  `TONG_DURATION` int(11) DEFAULT NULL,
  `CALL_RESULT` varchar(4) NOT NULL,
  `EXTENSION_NO` varchar(20) NOT NULL,
  `COM_CD` varchar(10) NOT NULL,
  `CALL_ID` varchar(50) NOT NULL,
  `TONG_USER` varchar(45) DEFAULT NULL,
  `PBX_TYPE` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`CALL_RESULT`,`CALL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=euckr;

CREATE TABLE `t_company` (
  `COM_CD` varchar(4) NOT NULL,
  `COM_NM` varchar(50) DEFAULT NULL,
  `COM_UPJONG` varchar(4) DEFAULT NULL,
  `COM_OWNER` varchar(30) DEFAULT NULL,
  `COM_ADDR1` varchar(120) DEFAULT NULL,
  `COM_TELNO1` varchar(20) DEFAULT NULL,
  `COM_TELNO2` varchar(20) DEFAULT NULL,
  `COM_TELNO3` varchar(20) DEFAULT NULL,
  `WOO_NO` varchar(8) DEFAULT NULL,
  PRIMARY KEY (`COM_CD`),
  KEY `idx_T_COMPANY01` (`COM_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=euckr;

CREATE TABLE `t_customer` (
  `COM_CD` varchar(4) NOT NULL,
  `CUSTOMER_ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `CUSTOMER_NM` varchar(20) DEFAULT NULL,
  `C_TELNO` varchar(20) DEFAULT NULL,
  `H_TELNO` varchar(20) DEFAULT NULL,
  `FAX_NO` varchar(20) DEFAULT NULL,
  `COMPANY` varchar(100) DEFAULT NULL,
  `DEPARTMENT` varchar(100) DEFAULT NULL,
  `JOB_TITLE` varchar(100) DEFAULT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `CUSTOMER_TYPE` varchar(4) DEFAULT NULL,
  `WOO_NO` varchar(8) DEFAULT NULL,
  `CUSTOMER_ADDR` varchar(120) DEFAULT NULL,
  `CUSTOMER_ETC` varchar(100) DEFAULT NULL,
  `C_TELNO1` varchar(20) DEFAULT NULL,
  `H_TELNO1` varchar(20) DEFAULT NULL,
  `UPDATE_DATE` varchar(14) DEFAULT NULL,
  PRIMARY KEY (`CUSTOMER_ID`),
  KEY `idx_T_CUSTOMER01` (`COM_CD`,`CUSTOMER_ID`),
  KEY `idx_T_CUSTOMER02` (`C_TELNO1`),
  KEY `idx_T_CUSTOMER03` (`H_TELNO1`)
) ENGINE=InnoDB AUTO_INCREMENT=4862 DEFAULT CHARSET=euckr;

CREATE TABLE `t_customer_history` (
  `COM_CD` varchar(4) NOT NULL,
  `CUSTOMER_ID` bigint(20) unsigned NOT NULL,
  `TOND_DD` varchar(8) NOT NULL,
  `TONG_TIME` varchar(6) NOT NULL,
  `TONG_USER` varchar(45) NOT NULL,
  `CALL_TYPE` varchar(1) DEFAULT NULL,
  `CONSULT_RESULT` varchar(4) DEFAULT NULL,
  `CONSULT_TYPE` varchar(4) DEFAULT NULL,
  `TONG_CONTENTS` varchar(100) DEFAULT NULL,
  `TONG_TELNO` varchar(20) DEFAULT NULL,
  `TELNO_TYPE` varchar(4) DEFAULT NULL,
  `CUSTOMER_NM` varchar(20) DEFAULT NULL,
  `BK_YN` varchar(1) DEFAULT NULL,
  `HANDLE_TYPE` varchar(1) DEFAULT '0',
  `CALL_BACK_YN` varchar(1) DEFAULT 'N',
  `CALL_BACK_RESULT` varchar(1) DEFAULT '2',
  `CALL_BACK_AGENT` varchar(50) DEFAULT NULL,
  `UPDATE_DATE` varchar(14) DEFAULT NULL,
  `PREV_TONG_DD` varchar(8) DEFAULT NULL,
  `PREV_TONG_TIME` varchar(6) DEFAULT NULL,
  `PREV_TONG_USER` varchar(45) DEFAULT NULL,
  `TRANS_YN` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`COM_CD`,`CUSTOMER_ID`,`TOND_DD`,`TONG_TIME`,`TONG_USER`),
  KEY `idx_T_CUSTOMER_HISTORY01` (`COM_CD`,`CUSTOMER_ID`,`TOND_DD`,`TONG_TIME`,`TONG_USER`),
  KEY `idx_T_CUSTOMER_HISTORY02` (`COM_CD`,`TOND_DD`,`TONG_TIME`,`TONG_USER`),
  KEY `idx_T_CUSTOMER_HISTORY03` (`CUSTOMER_NM`),
  KEY `idx_T_CUSTOMER_HISTORY04` (`PREV_TONG_DD`,`PREV_TONG_TIME`,`PREV_TONG_USER`,`TRANS_YN`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=euckr;

CREATE TABLE `t_customer_temp` (
  `COM_CD` varchar(4) NOT NULL,
  `CUSTOMER_ID` bigint(20) unsigned DEFAULT NULL,
  `TEMP_ID` varchar(20) DEFAULT NULL,
  `CUSTOMER_NM` varchar(20) DEFAULT NULL,
  `C_TELNO` varchar(20) DEFAULT NULL,
  `H_TELNO` varchar(20) DEFAULT NULL,
  `FAX_NO` varchar(20) DEFAULT NULL,
  `COMPANY` varchar(100) DEFAULT NULL,
  `DEPARTMENT` varchar(100) DEFAULT NULL,
  `JOB_TITLE` varchar(100) DEFAULT NULL,
  `EMAIL` varchar(100) DEFAULT NULL,
  `CUSTOMER_TYPE` varchar(4) DEFAULT NULL,
  `WOO_NO` varchar(8) DEFAULT NULL,
  `CUSTOMER_ADDR` varchar(120) DEFAULT NULL,
  `CUSTOMER_ETC` varchar(100) DEFAULT NULL,
  `C_TELNO1` varchar(20) DEFAULT NULL,
  `H_TELNO1` varchar(20) DEFAULT NULL,
  `SUSPEND_YN` varchar(1) DEFAULT NULL,
  `UPDATE_DATE` varchar(14) DEFAULT NULL,
  PRIMARY KEY (`CUSTOMER_ID`),
  KEY `idx_T_CUSTOMER01` (`COM_CD`,`CUSTOMER_ID`),
  KEY `idx_T_CUSTOMER02` (`C_TELNO1`),
  KEY `idx_T_CUSTOMER03` (`H_TELNO1`)
) ENGINE=InnoDB AUTO_INCREMENT=4862 DEFAULT CHARSET=euckr;

CREATE TABLE `t_customer_history_temp` (
  `COM_CD` varchar(4) NOT NULL,
  `CUSTOMER_ID` bigint(20) unsigned DEFAULT NULL,
  `TEMP_ID` varchar(20) DEFAULT NULL,
  `TOND_DD` varchar(8) NOT NULL,
  `TONG_TIME` varchar(6) NOT NULL,
  `TONG_USER` varchar(45) NOT NULL,
  `CALL_TYPE` varchar(1) DEFAULT NULL,
  `CONSULT_RESULT` varchar(4) DEFAULT NULL,
  `CONSULT_TYPE` varchar(4) DEFAULT NULL,
  `TONG_CONTENTS` varchar(100) DEFAULT NULL,
  `TONG_TELNO` varchar(20) DEFAULT NULL,
  `TELNO_TYPE` varchar(4) DEFAULT NULL,
  `CUSTOMER_NM` varchar(20) DEFAULT NULL,
  `BK_YN` varchar(1) DEFAULT NULL,
  `HANDLE_TYPE` varchar(1) DEFAULT '0',
  `CALL_BACK_YN` varchar(1) DEFAULT 'N',
  `CALL_BACK_RESULT` varchar(1) DEFAULT '2',
  `CALL_BACK_AGENT` varchar(50) DEFAULT NULL,
  `UPDATE_DATE` varchar(14) DEFAULT NULL,
  `PREV_TONG_DD` varchar(8) DEFAULT NULL,
  `PREV_TONG_TIME` varchar(6) DEFAULT NULL,
  `PREV_TONG_USER` varchar(45) DEFAULT NULL,
  `TRANS_YN` varchar(1) DEFAULT NULL,
	`SUSPEND_YN` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`COM_CD`,`CUSTOMER_ID`,`TOND_DD`,`TONG_TIME`,`TONG_USER`),
  KEY `idx_T_CUSTOMER_HISTORY01` (`COM_CD`,`CUSTOMER_ID`,`TOND_DD`,`TONG_TIME`,`TONG_USER`),
  KEY `idx_T_CUSTOMER_HISTORY02` (`COM_CD`,`TOND_DD`,`TONG_TIME`,`TONG_USER`),
  KEY `idx_T_CUSTOMER_HISTORY03` (`CUSTOMER_NM`),
  KEY `idx_T_CUSTOMER_HISTORY04` (`PREV_TONG_DD`,`PREV_TONG_TIME`,`PREV_TONG_USER`,`TRANS_YN`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=euckr;

CREATE TABLE `t_customer_telno` (
  `COM_CD` varchar(4) NOT NULL,
  `CUSTOMER_ID` bigint(20) unsigned NOT NULL,
  `TELNO_TYPE` varchar(4) DEFAULT NULL,
  `TELNO` varchar(20) NOT NULL,
  PRIMARY KEY (`COM_CD`,`CUSTOMER_ID`,`TELNO`),
  KEY `idxt_customer_telno01` (`COM_CD`,`CUSTOMER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=euckr;

CREATE TABLE `t_files` (
  `SEQNUM` int(11) NOT NULL AUTO_INCREMENT,
  `FNAME` varchar(100) NOT NULL,
  `FTIME` varchar(50) NOT NULL,
  `FLOC` varchar(200) NOT NULL,
  `FSIZE` varchar(100) NOT NULL,
  PRIMARY KEY (`SEQNUM`),
  UNIQUE KEY `SEQNUM` (`SEQNUM`)
) ENGINE=MyISAM DEFAULT CHARSET=euckr;


CREATE TABLE `t_inner_work` (
  `COM_CD` varchar(4) NOT NULL,
  `JUPSU_DD` varchar(8) NOT NULL,
  `JUPSU_NO` varchar(40) NOT NULL,
  `JUPSUJA` varchar(40) NOT NULL,
  `CHURYJA` varchar(40) DEFAULT NULL,
  `CUSTOMER_ID` decimal(18,0) DEFAULT NULL,
  `JUPSU_CONTENTS` varchar(500) DEFAULT NULL,
  `CHURY_DD` varchar(8) DEFAULT NULL,
  `GUBUN` varchar(1) DEFAULT NULL,
  `CHURY_CONTENTS` varchar(500) DEFAULT NULL,
  `CUSTOMER_NM` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`COM_CD`,`JUPSU_DD`,`JUPSU_NO`,`JUPSUJA`),
  KEY `idx_T_INNER_WORK01` (`COM_CD`,`JUPSU_DD`,`JUPSU_NO`,`JUPSUJA`)
) ENGINE=InnoDB DEFAULT CHARSET=euckr;


CREATE TABLE `t_l_code` (
  `COM_CD` varchar(4) NOT NULL,
  `L_MENU_CD` varchar(3) NOT NULL,
  `L_MENU_NM` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`COM_CD`,`L_MENU_CD`),
  KEY `idx_T_L_CODE01` (`COM_CD`,`L_MENU_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=euckr;


CREATE TABLE `t_l_menu` (
  `L_MENU_CD` varchar(3) NOT NULL,
  `L_MENU_NM` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`L_MENU_CD`),
  KEY `idx_T_L_MENU01` (`L_MENU_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=euckr;


CREATE TABLE `t_license` (
  `COM_CD` varchar(4) NOT NULL,
  `LINCESE_START_DD` varchar(8) DEFAULT NULL,
  `LICENSE_TYPE` varchar(1) DEFAULT NULL,
  `LICENSE_END_DD` varchar(8) DEFAULT NULL,
  PRIMARY KEY (`COM_CD`),
  KEY `idx_T_LICENSE01` (`COM_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=euckr;


CREATE TABLE `t_noreceive` (
  `SEQNUM` int(11) NOT NULL AUTO_INCREMENT,
  `RECEIVER` varchar(20) NOT NULL,
  `TIME` varchar(50) NOT NULL,
  `CONTENT` text NOT NULL,
  `FORM` varchar(5) NOT NULL,
  `SENDER` varchar(20) NOT NULL,
  `NMODE` varchar(5) NOT NULL,
  `LOC` varchar(11) NOT NULL,
  `NTITLE` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`SEQNUM`)
) ENGINE=InnoDB AUTO_INCREMENT=34 DEFAULT CHARSET=euckr;


CREATE TABLE `t_notices` (
  `SEQNUM` int(11) NOT NULL AUTO_INCREMENT,
  `NTIME` varchar(50) NOT NULL,
  `CONTENT` text NOT NULL,
  `SENDER` varchar(20) NOT NULL,
  `NMODE` varchar(5) NOT NULL,
  `ntitle` varchar(200) NOT NULL,
  PRIMARY KEY (`SEQNUM`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=euckr;


CREATE TABLE `t_s_code` (
  `COM_CD` varchar(4) NOT NULL,
  `L_MENU_CD` varchar(3) NOT NULL,
  `S_MENU_CD` varchar(4) NOT NULL,
  `S_MENU_NM` varchar(30) DEFAULT NULL,
  `MODIFY_YN` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`COM_CD`,`L_MENU_CD`,`S_MENU_CD`),
  KEY `idx_T_S_CODE01` (`COM_CD`,`L_MENU_CD`,`S_MENU_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=euckr;


CREATE TABLE `t_s_menu` (
  `L_MENU_CD` varchar(3) NOT NULL,
  `S_MENU_CD` varchar(2) NOT NULL,
  `S_MENU_NM` varchar(20) DEFAULT NULL,
  `FORM_NM` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`L_MENU_CD`,`S_MENU_CD`),
  KEY `idx_T_S_MENU01` (`L_MENU_CD`,`S_MENU_CD`)
) ENGINE=InnoDB DEFAULT CHARSET=euckr;

CREATE TABLE `t_schedule` (
  `COM_CD` varchar(4) NOT NULL,
  `S_START_TIME` varchar(12) NOT NULL,
  `REGISTRANT` varchar(45) NOT NULL,
  `SHARING_TYPE` varchar(2) NOT NULL DEFAULT 'P' COMMENT '공유일정:S, 개인일정:P, 외근일정:O',
  `S_TITLE` varchar(50) NOT NULL,
  `S_END_TIME` varchar(12) DEFAULT NULL,
  `S_DESC` varchar(200) DEFAULT NULL,
  `S_COMPANY_COWORKER` varchar(300) NOT NULL DEFAULT '',
  `S_WORKOUT_REASON` varchar(4) DEFAULT NULL COMMENT '외근이유',
  `S_WORKOUT_LOC` varchar(30) DEFAULT NULL COMMENT '외근장소',
  PRIMARY KEY (`COM_CD`,`S_START_TIME`,`REGISTRANT`,`SHARING_TYPE`,`S_TITLE`,`S_COMPANY_COWORKER`),
  KEY `idx_T_SCHEDULE201` (`COM_CD`,`S_START_TIME`,`REGISTRANT`,`SHARING_TYPE`,`S_TITLE`,`S_COMPANY_COWORKER`)
) ENGINE=InnoDB DEFAULT CHARSET=euckr;

CREATE TABLE `t_user` (
  `COM_CD` varchar(4) NOT NULL,
  `USER_ID` varchar(20) NOT NULL,
  `USER_NM` varchar(20) DEFAULT NULL,
  `USR_HP` varchar(20) DEFAULT NULL,
  `ADDR1` varchar(120) DEFAULT NULL,
  `WOO_NO` varchar(8) DEFAULT NULL,
  `H_TELNO` varchar(20) DEFAULT NULL,
  `DEPART_CD` varchar(4) DEFAULT NULL,
  `GRADE` varchar(4) DEFAULT NULL,
  `EXTENSION_NO` varchar(10) DEFAULT NULL,
  `WORK_TYPE` varchar(4) DEFAULT NULL,
  `ENTERING_DD` varchar(8) DEFAULT NULL,
  `RETIRE_DD` varchar(8) DEFAULT NULL,
  `USER_EMAIL` varchar(30) DEFAULT NULL,
  `DEPART_NM` varchar(30) DEFAULT NULL,
  `USER_PWD` varchar(50) DEFAULT NULL,
  `WORK_AREA` varchar(2) DEFAULT NULL,
  `TEAM_CD` varchar(4) DEFAULT NULL,
  `TEAM_NM` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`COM_CD`,`USER_ID`),
  KEY `idx_T_USER01` (`COM_CD`,`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=euckr;


CREATE TABLE `t_workout` (
  `COM_CD` varchar(4) NOT NULL,
  `USER_ID` varchar(20) NOT NULL,
  `WORKOUT_DD` varchar(14) NOT NULL,
  `WORKOUT_REASON` varchar(4) DEFAULT NULL,
  `WORKOUT_LOC` varchar(30) DEFAULT NULL,
  `WORKOUT_DESC` varchar(100) DEFAULT NULL,
  `COMPANY_COWORKER` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`COM_CD`,`USER_ID`,`WORKOUT_DD`),
  KEY `idx_T_WORKOUT01` (`COM_CD`,`USER_ID`,`WORKOUT_DD`)
) ENGINE=InnoDB DEFAULT CHARSET=euckr;


CREATE TABLE `t_zipcode` (
  `ZIPCODE` varchar(7) NOT NULL DEFAULT '',
  `SEQ` int(6) NOT NULL DEFAULT '0',
  `SIDO` varchar(4) NOT NULL DEFAULT '',
  `GUGUN` varchar(17) NOT NULL DEFAULT '',
  `DONG` varchar(26) NOT NULL DEFAULT '',
  `RI` varchar(45) NOT NULL DEFAULT '',
  `BUNJI` varchar(17) NOT NULL DEFAULT '',
  PRIMARY KEY (`ZIPCODE`,`SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=euckr;

CREATE TABLE `t_auditlog` (
  `COM_CD` varchar(4) NOT NULL,
  `USER_ID` varchar(20) NOT NULL,
  `AUDIT_DD` varchar(14) NOT NULL,
  `AUDIT_CD` varchar(4) DEFAULT NULL,
  `AUDIT_DESC` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`COM_CD`,`USER_ID`,`AUDIT_DD`),
  KEY `idx_T_AUDITLOG01` (`COM_CD`,`USER_ID`,`AUDIT_DD`)
) ENGINE=InnoDB DEFAULT CHARSET=euckr;

